
DROP TABLE IF EXISTS usersdb;

CREATE TABLE usersdb (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    username TEXT NOT NULL,
    userrole TEXT NOT NULL,
    usertoken TEXT NOT NULL
);